### PR TITLE
[Fix] No more issues at the end of the execution with simple and minimal solution.

### PR DESCRIPTION
**Pull request by MicheleGuerriero**
No more issues at the end of the execution with simple and minimal solution. @affo take a look!

### CODE REVIEW

**Comment by affo** [comment]
Good morning @MicheleGuerriero !

Would you mind changing this:

```
if is_xmas then
    say ("")
        help_elves
    elseif no_elves = max_elves then
        help_elves
    end
```

to something like:

```
if is_xmas or no_elves = max_elves then
    help_elves
end

if is_xmas then
    say ("")
end
```

Second would you mind setting `is_ready := true` after saying that the sleigh has been prepared?

Sorry for being so pignolo :)

**Comment by MicheleGuerriero** [comment]
ahahah no problem at all, trust me I've seen much bigger pignoli!! going to fix in the upcoming commit.
As for the second fix I'm also going to move "is_busy = true" after saying "helping elves".

**Comment by MicheleGuerriero** [comment]
Updated. I just realized that yesterday I forgot to fix the tabbing problem, I'm sorry. Probably we can fix this in an isolated commit after merging this. Wdyt?

**Comment by affo** [comment]
For sure!  
I am looking forward to merging this PR!
Don't you squash the 2 commits?

**Comment by MicheleGuerriero** [comment]
Squashed!

**Pull request merged**
